FROM node:22-alpine

ARG TOKEN_API_PANDASCORE

## Mysql
# Production
ARG BDD_TARGET
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_HOST

# Mongo
# Production
ARG BDD_TARGET
ARG DB_PORT
ARG MONGO_INITDB_ROOT_USERNAME
ARG MONGO_INITDB_ROOT_PASSWORD
ARG DB_NAME
ARG DB_HOST

# DynamoDB
# Production
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG DYNAMODB_TABLE


ENV PORT=${PORT}
ENV TOKEN_API_PANDASCORE=${TOKEN_API_PANDASCORE}
ENV BDD_TARGET=${BDD_TARGET}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_NAME=${DB_NAME}
ENV DB_HOST=${DB_HOST}
ENV MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
ENV MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}

WORKDIR /app
COPY . .
RUN npm install
CMD [ "node", "main.js" ]

EXPOSE 80