name: CI/CD Pipeline

on:
  push:
    branches: ["main", "feature/**", "bugFix/**", "hotFix/**","fix/**"]
  pull_request:
    branches: ["feature/**", "bugFix/**","hotFix/**"]

jobs:
  lint-and-test:
    name: "🔍 Lint & Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: src/package-lock.json
          registry-url: "https://npm.pkg.github.com"
          scope: "@hugo38rodrigues"

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  build-and-push:
    name: "🐳 Build & Push Docker"
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        run: echo "VERSION=$(node -p "require('./src/package.json').version")" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git tag v${{ env.VERSION }} || echo "::warning::Tag v${{ env.VERSION }} existe déjà, skipping."
          git push origin v${{ env.VERSION }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-hall-e:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api-hall-e:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: github_token=${{ secrets.GH_TOKEN }}