name: CI/CD Pipeline

on:
  push:
    branches: [main, feature/**]

jobs:
  build-and-push:
    name: '🐳 Build & Push Docker Image'
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Setup Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Build & Push
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg GITHUB_TOKEN=${GH_TOKEN} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/match_recoveries:${{ env.VERSION }} \
            --push .
